### ISSUE TITLE
sorter.bash script produce different output files

### ISSUE THREAD

**Issue by HubLot** [NMRLipids/nmrlipids.blogspot.fi#19]
I try to regenerate the `sortedForPlot` folder from the script `sorter.bash` to produce the `comparisonSorted.pdf` figure but the sorted data files produced by the script are different from the ones in the repository.
For example with the `sortedForPlot/POPC/KUKOL-298K_blogged-20-09-14.dat` (the github version appears in red and the one from the script appears in green) :

``` diff
--- a/DATAreportediINblog/sortedForPlot/POPC/KUKOL-298K_blogged-20-09-14.dat
+++ b/DATAreportediINblog/sortedForPlot/POPC/KUKOL-298K_blogged-20-09-14.dat
@@ -1,9 +1,9 @@
-1.05   -0.0595
-1.05   0.0087
-2.45   -0.1202
-2.45   -0.1357
-2.6    0.171045
-2.6    0.1116
-3.7    0.1497
-5.15   -0.0161
-5.15   -0.2257
+1.25   -0.0595
+1.25   0.0087
+1.8    -0.1202
+1.8    -0.1357
+3.15   0.171045
+3.15   0.1116
+4.15   0.1497
+5.25   -0.0161
+5.25   -0.2257
```

The x data are not the same. Hence, in the resulting pdf, the points are not the same spot (see the orange dots on g3 column) :
![comparisonsorted](https://cloud.githubusercontent.com/assets/1273176/6830763/53efca4e-d31c-11e4-8bc3-f60a26fe782f.png)

@markussmiettinen is the `sorter.bash` script in the repo outdated ?

Thanks.

**Comment by markussmiettinen** [comment]
I do not think there was any actual bug in the script. Maybe the x-values changed (compared to earlier values) simply because the actual data files had changed, and thus the sorting changed?

Anyhow, I just created a comparisonSorted.pdf that is up to date. (And also found (and fixed) a small bug in the sorter.bash: It got confused if OP:s started with the +sign.)

**Comment by HubLot** [comment]
Okay, I didn't realized that the sorting was automatic and depended on the data files...
