### ISSUE TITLE
Cannot use plotDataSorted.gpl properly

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/nmrlipids.blogspot.fi#3]
I cannot reproduce the figure comparisonSorted.pdf with nmrlipids.blogspot.fi/DATAreportediINblog/plotDataSorted.gpl properly. Thus I cannot change the force field names in the figure to correspond the names in the table 1. The current names in the table 1 are the ones we are going to use. The names are either used already in the literature, or then approved by the authors of the original papers.

Markus, can you update the names in the figure?

**Comment by markussmiettinen** [comment]
The names in the figure have been updated.

Samuli, if your problem with updating the figure was not related to (e.g.) missing data, but for example of your version of gnuplot not being compatible with mine, maybe you can close this issue? If not, then maybe you describe in more detail the problem(s) you encountered?
