### ISSUE TITLE
CHARMM36 72 lipids: Which version of FF parameters?

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/nmrlipids.blogspot.fi#30]
Samuli, could you check which version of the CHARMM36 force field parameters you actually used for the 72-lipid POPC and DPPC simulations? I wrote now in the manuscript the version I used (Sep 2013 from MacKerell web site) to create the starting files, but you might in principle have used something else (such as the Piggot files or later versions from MacKerell). Please check and correct the text if needed.

**Comment by ohsOllila** [comment]
This is what I have used. The text is correct.
