### ISSUE TITLE
Mistake on results with Chiu model fixed in data in github

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/nmrlipids.blogspot.fi#33]
I had a mistake in ffgmx2.hdb file when calculating the order parameters from POPC simulations with Chiu model. The mistake led to the large value of g2 order parameters. I have now corrected the mistake, see
https://github.com/NMRLipids/nmrlipids.blogspot.fi/commit/a2004320705e767f91f1a0a5e73554b96cc5b9f8

The new results are in https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/DATAreportediINblog/POPC/CHIU-298K_recalculated-04-05-15.dat

Also other order parameters are changed slightly since all the atoms are now inside box, opposite to old results. These changes do not affect anything in practise.

However, the other figures should be updated due to the change in the g2 result.

**Comment by markussmiettinen** [comment]
I have now updated Fig 2 and Fig 4 using the recalculated data. Other figures are not affected, right?

**Comment by ohsOllila** [comment]
Yes, other figures are not affected.
