### ISSUE TITLE
Font issues (figures 7 and 8)

### ISSUE THREAD

**Issue by mattijavanainen** [NMRLipids/nmrlipids.blogspot.fi#35]
Fig. 8 suffers from an unreadably small font size on the axis labels. Fig. 7, on the other hand, suffers from a bad choice of text colour (yellow) which makes it hard to read. Additionally, Fig. 7 is cropped so that some parts of the letters in the text next to the y axis are missing.

**Comment by ohsOllila** [comment]
The color coding is uniform throughout the manuscript. It may not be optimal for the Fig. 7 but is otherwise good, so I suggest that we do not change it. It would require changes in several other places as well. Other issues mentioned should be fixed.

**Comment by markussmiettinen** [comment]
Thanks! I think I can do something to address all of these issues. Points 1) and 3) are easy. Point 2) might be fixable by making the font larger... which might require dropping the yellow "S_CH"-texts. Let's see.

**Comment by markussmiettinen** [comment]
All three points should now be fixed. Matti, if you agree, please close the issue.
