### ISSUE TITLE
outdated files in HGmodelMANUSCRIPT folder?

### ISSUE THREAD

**Issue by HubLot** [NMRLipids/nmrlipids.blogspot.fi#40]
I noticed some old folders/files in the `HGmodelMANUSCRIPT` directory:
- `DATAforCHOLfig`: I didn't find any use of this folder (`grep -R "DATAforCHOLfig" *) on the whole repository) so maybe it can be removed.
- `DATAforDEHYDRATIONfig` is used in `DATAreportediINblog/POPC/dehydration/BERGER-298K.dat`and `DATAreportediINblog/DMPC/dehydration/EXP-Dvinskikh2005b_COUPLINGS.dat`. If it's not redondant, could it be moved to DATAreportediINblog ?
- `comparison3.pdf` is only used in older versions of the manuscript so it can be safely moved to `OLDversions`

**Comment by ohsOllila** [comment]
I have now removed the DATAforCHOLfig and DATAforDEHYDRATIONfig files, and moved comparison3.pdf. These were temporary files for Markus to make plots some time ago and he marked into the data where it had been taken. I also updated the information in these files to the original source of the data: https://github.com/NMRLipids/nmrlipids.blogspot.fi/commit/86e8173cc2c3cf2cd2558ab35ceff291c47c626d
