### ISSUE TITLE
Initial capital letters on axis labels

### ISSUE THREAD

**Issue by mattijavanainen** [NMRLipids/nmrlipids.blogspot.fi#42]
According to the ACS style guide, the axis labels should have their initial letters capitalised. This is not the case in Figs. 8 and 9 at the moment.

**Comment by markussmiettinen** [comment]
Thanks, they are now. (Wrt Fig 9, I only changed the gnuplot script and the corresponding pdf. That is, the change will only become visible once we lock the line types for Fig 9.)
