### ISSUE TITLE
Exactly same PN-angle twice in DLPC dehydration data

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/nmrlipids.blogspot.fi#54]
In the DLPC Berger dehydration PN-angle data (https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/DATAreportediINblog/DLPC/dehydration/PN-vector/Berger-300K.dat) there seems to be a bug: The exactly same numerical value is given for the average PN-angle at 28 w/l and 24 w/l:

> # n_w/l   PN angle (degrees)
> 
> 28 75.57771684011664
> 26 75.16919793218835
> 24 75.57771684011664

**Comment by matejkanduc** [comment]
Thanks for noticing, the 24 w/l should be:
24 75.8974

**Comment by markussmiettinen** [comment]
Good, thanks. Fixed now.
