### ISSUE TITLE
Figure 8: CHARMM36 @40w/l missing

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/nmrlipids.blogspot.fi#55]
Data points for which order parameters are given in Fig. 7 are missing the average PN-vector angle in Fig. 8:

[1] CHARMM36 @ 40 w/l
[2] MacRog @ 43.75 w/l

**Comment by ohsOllila** [comment]
I added the data and the scripts used: https://github.com/NMRLipids/nmrlipids.blogspot.fi/commit/010072b9f706a46f43feb0a83079685000da3a0f

However, I had wrong gnuplot version and the figure is not good:
 https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/2d4e2a1c889f7be702f9f740a8b6b2953ea0f623/Fig/dehydrationPN.pdf

Please run this with correct version and push.

**Comment by markussmiettinen** [comment]
I updated the [figure](https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/Fig/dehydrationPN.pdf).

I also had updated my gnuplot to 5.0 in between, so had to update the [script](https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/Fig/scripts/plotDehydrationPNvector.gpl) a bit too; for example the dashed lines are done [differently](https://groups.google.com/forum/#!topic/comp.graphics.apps.gnuplot/p02fDja_G_w) in 5.0.
