### ISSUE TITLE
Answer to reviewer's point 1

### ISSUE THREAD

**Issue by mattijavanainen** [NMRLipids/nmrlipids.blogspot.fi#57]
I think we can explicitly point out in our response that especially lipids compatible with Charmm and Amber force fields have been updated recently to be used in the NPT ensemble. We can also mention this in the beginning of the methods section in the SI.

I'd then add to the reply something along:

... NPT ensemble with zero tension. _Most notably, the two popular lipid force fields that required the use of either a fixed membrane area or a nonzero surface tension, Charmm27 and Lipid11, were recently updated to Charmm36 and Lipid14, which removed this unrealistic requirement. This is also mentioned in the updated manuscript._ The improvements of ...

**Comment by ohsOllila** [comment]
I have now updated the answer and the text related to this, see https://github.com/NMRLipids/nmrlipids.blogspot.fi/commit/da1c90192a773d597d45b41ae51657bc6af3ffe1
