### ISSUE TITLE
Answer to reviewer's point 3

### ISSUE THREAD

**Issue by mattijavanainen** [NMRLipids/nmrlipids.blogspot.fi#58]
The reply now says: "The quantification used is explained in the figure caption." However, the explanation is very qualitative. In my opinion we need to add the quantitative criteria in the SI and point to it in the caption of figure 4. The given criteria must include **numerical** boundaries on which the ranking/categorisation is based on in figure 4 rather than vague expressions such as "almost within experimental error" etc.

**Comment by jsmaatta** [comment]
I very much like Matti's idea here. We could do it similarly to the Fig. 1 in this paper published by Pande's group. http://pubs.acs.org/doi/pdf/10.1021/ct2007814

Just use the color bar (of the error compared to experiments, with numbers) on the side and divide it to the four regions (from green to red) that we have in Figure 4.

**Comment by markussmiettinen** [comment]
I created numerical limits for the assessment, and described the whole process of assessment in SI.

Fig 4 changed slightly, as I needed to simplify the assessment to make it shorter to describe. The main message, of course, remains unchanged, as Fig 4 is simply an interpretation of the data given in Fig 2.

The color bar approach, while appealing, was not feasible in this context.
