### ISSUE TITLE
dehydration.pdf and cholesterolization.pdf

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/nmrlipids.blogspot.fi#6]
Markus, please specify which criteria is used to shift the data in dehydration.pdf and cholesterolization.pdf? 

How have you done these figures (gnuplot or something else)? Would it be possible to share the source file, or somehow the information which data sets are excatly used? I should check that the data correspoding to the table 2 is really used.

**Comment by ohsOllila** [comment]
The properly calculated results for GAFFlipid in low hydration (7 water/lipid) is now added to https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/DATAreportediINblog/POPC/dehydration/GAFF-303K_7WperL_added-17-02-15.dat

The properly calculated CHARMM36 data now added to the nmrlipids.blogspot.fi/DATAreportediINblog/POPC/dehydration/ folder. The system with 31 water/lipid was already in 
https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/DATAreportediINblog/POPC/CHARMM36-303K_blogged-20-11-13.dat

**Comment by ohsOllila** [comment]
The data for POPC cholesterol mixtures delivered by Fernando Favela on February 24, 2015 at 5:59 AM should be included into the cholesterol plot:
http://nmrlipids.blogspot.com/p/the-project-has-been-success-by-this-far.html
https://dl.dropboxusercontent.com/u/11027999/charmm36_popc%2Bchol.tar.gz

**Comment by markussmiettinen** [comment]
I now clarified the shifting-issue in the captions of those figures (in HGmodel_ACStemplate.tex) and also added the scripts (plotCholesterolData.gpl and plotDehydrationData.gpl) to github.

**Comment by HubLot** [comment]
Great. I just put here the hash of the commits for easy reference:
e7c41d9b22943c96cfeba3872e303715fe7d7b2d 943960cd926eb277ee6b8f3b2766eb87d14b558d 446b29b41509591ac00580a1bc76329c2e4efadf 5abdc5650ae279d69533a97028e97c75e418a47e

**Comment by HubLot** [comment]
Unfortunately, in the 2 gnuplot scripts `plotCholesterolData.gpl` and `plotDehydrationData.gpl`, there is paths to absent data file. For example, "./DPPC/cholesterol/EXP-Brown1978.dat" in  `plotCholesterolData.gpl` is not in the repo.

**Comment by markussmiettinen** [comment]
Yes, I knew this (missing data) to be the case, but shared the scripts anyhow already now because of Samuli's request to do so. It would take me some time to get the data files in place (because I did them in a hurry before to BPS meeting and they lack metadata), and I do not have that time now, but I understood Samuli plans to work on this.

**Comment by HubLot** [comment]
Okay. No problem

**Comment by ohsOllila** [comment]
I have now added the data by Fernando Favela in the format that it can used on the cholesterol plot. I have also modified the gnuplot script accordingly. I did not produce new figure yet, however, due to the missing data files.
https://github.com/NMRLipids/nmrlipids.blogspot.fi/commit/85c543da8bd510d81c9bdaf1dfcae0846c3c031a

**Comment by ohsOllila** [comment]
The data in the dehydration figure and the figure itself should be up-to-date now.

**Comment by ohsOllila** [comment]
Some of things discussed here are fixed and some not. I close this and create new ones.
