### ISSUE TITLE
TOC graphic

### ISSUE THREAD

**Issue by mattijavanainen** [NMRLipids/nmrlipids.blogspot.fi#60]
In the version of Patrick (modified by Samuli): the small text will not be readable when the figure is shrank to 8.5 cm × 4.75 cm.  Also, symbols on top of the lipid (g_1 etc.) will probably not be readable, especially in B&W. A minor thing to note is that the aspect ratio of the PP slide is probably not correct but this will only means that not all the space available for the TOC graphic will be used.

**Comment by ohsOllila** [comment]
I have now increased the fonts and shrunk to the real size: https://github.com/NMRLipids/nmrlipids.blogspot.fi/commit/c33b8fee1039253ab37028e2eb1061d4c20aa66e

**Comment by ohsOllila** [comment]
Discussion continued here: https://github.com/NMRLipids/nmrlipids.blogspot.fi/issues/61
