### ISSUE TITLE
Voting for the TOC figure

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/nmrlipids.blogspot.fi#61]
We have now two different suggestions for the TOC figure:
1.
![tocs](https://cloud.githubusercontent.com/assets/7114769/9328673/606cf8e6-45b3-11e5-891c-e10d3539cd2f.png)

2.

![toc](https://cloud.githubusercontent.com/assets/7114769/9328697/95af8816-45b3-11e5-924c-9f612c1b25e0.png)

I think that both are good but we can choose only one. Let us know if you prefer one over another.

Note that the 1. is in real size already, but 2. is to be shrinked.

**Comment by mattijavanainen** [comment]
Actually 2. does not require resizing since it's now 300 dpi and 8.5 cm*4.75 cm, just as the guidelines suggest (http://pubs.acs.org/paragonplus/submission/toc_abstract_graphics_guidelines.pdf)

**Comment by ohsOllila** [comment]
Yes, but when I made this issue the 2. became bigger above when I imported it (at least I see it bigger). I had to convert it png to put it here. I do not have time now to do it better.

**Comment by mattijavanainen** [comment]
The guidelines document requests 300 dpi, so the resolution for a figure of 3.25 in \* 1.75 in will be 975*525. I don't know why gimp did not give me this exact resolution with the export function, but it's close to the correct size at least.

**Comment by HubLot** [comment]
The 2 TOC are really nice. Thanks to their authors.

I prefer the 2nd TOC with a minor change: the labeled carbons in the lipid sketch could be colored (in black). For example, it's not clear where is the g1 carbon from an outside point of view: we know it's above the oxygen bond but someone else could think it's beneath.
If the carbons were in black (don't know how it will render in VMD) then it's straightforward. Or make a tiny arrow.

**Comment by jsmaatta** [comment]
Hi,
I think the 1st toc is more readable for the people that deal with experiments and the 2nd for people working with simulations.

Since the 2nd toc figure has the correct dimensions, I did a quick rearrange for the 1st figure to match those more closely. (Note that it needs to be redrawn with the high-quality original figures instead of simply resizing).
![toc](https://cloud.githubusercontent.com/assets/11630230/9335589/e2778056-45a2-11e5-84be-059ad87db89b.png)

-Jukka

**Comment by ohsOllila** [comment]
I liked Jukka's rearrangement idea and made a new figure. Thus the suggestions are now:
1.

![tocs](https://cloud.githubusercontent.com/assets/7114769/9341781/93c6d3c2-4600-11e5-9e89-1988d1d48cef.png)

2.

![toc](https://cloud.githubusercontent.com/assets/7114769/9341791/a4314c42-4600-11e5-9f58-af62862fb5dd.png)

After thinking this for a while, I prefer the option 1., mainly because it makes clear that we are discussing about the lipids in a liquid bilayer, not in a crystal or vacuum etc.

And now the option 1. is also with the correct resolution, thus the size is the same also in this display.

**Comment by ClaireLoison** [comment]
Hi, thanks for the nice TOCs ! Some toughts 
- Avantages of TOC1:
-  it clearly states that the experiment is NMR
-  it shows what is the structural observable  used to link the experiments to the MD simulations is theta
- the bilayer is shown
- Disadvantage of TOC1:
- the form of the NMR signals is not at the heart of the message of the article, but they take here a lot of space.
- I would not place the "?" near by the double arrow, but nearby the theta. the link between theta and NMR is clear, but the theta distribution is the unknown.
- Advantage of TOC2 : 
- for people familiar with lipid bilayer simulations, it gives a larger piece of information
- Disadvantage of TOC2 : 
- does not specify that the simulations are MD simulations, and that experiments are NMR experiments
- the representation of the lipid head is clearer in TOC1
- the order parameter is not defined

Here is a suggestion, sorry it is not usable as is...
![screen shot 2015-08-18 at 11 15 09 pm](https://cloud.githubusercontent.com/assets/11630548/9342946/10edb99e-45ff-11e5-965f-03dac14b0956.png)

Best, claire

**Comment by mretegan** [comment]
I've ray-traced again the lipid bilayer using Tachyon, changed the colors to be more neutral, and removed the red "zooming" lines because they were superfluous. There is a pull-request including the .svg file in case you want to tinker with the figure.

![toc](https://cloud.githubusercontent.com/assets/93124/9352663/53218188-4663-11e5-8670-b297acee88fb.png)

**Comment by lucamonticelli** [comment]
I vote for TOC1. 
Some more comments:
1, I do like the zoom-in lines, they point out that we focus on a (small) portion of the lipid molecule.
2, The NMR spectra take space, but then the entire work is based on a comparison with NMR data, so I think it's ok to leave them.
3, I do not like very much the figure of the bilayer with the lipid tails hanging in vacuum - that is not what we simulate. I think it's much better to show periodic images, sharply cut at the edges.
4, Finally, we might want to consider using 3 colors for the bilayer figure: one color for water, one color for the acyl chains, and one color for the head groups, which are relevant to out study. As an alternative, the head groups could use N colors: the same colors as the central figure.

**Comment by ohsOllila** [comment]
I think that the figure by Marius is again an improvement. Here are some comments, topics numbered as Luca:
1. I agree that we should have the zoom-in lines for the same reason as Luca.
2. I also think that we could keep the spectras even though they are not the heart of the article. The reason is that those might attract people with NMR backround to take a look and make them consider the potential of MD as an interpretation tool.
3. Marius, did you have perspective view activated when you rendered the bilayer? I think that the orthographic view would work better and then there should not be that much "lipid tails hangin in the vacuum". The sharp cut might work as well.

**Comment by mretegan** [comment]
Here is the new figure with the lipids rendered in an orthographic perspective. The tails are still visible, but in the end this is just a matter of personal preference. The only information that image has to provide is that MD simulations were performed on lipid bilayers, which it does. You can see similar representations on the Slipids web site or in the graphical abstract of the GAFFlipid paper.

![toc](https://cloud.githubusercontent.com/assets/93124/9358273/6d25cc2e-468b-11e5-905e-08c57bafca38.png)

**Comment by mattijavanainen** [comment]
I like this one a lot but I suggest these small modifications:
1) If possible, the size of all the symbols (associated with both the spectra and the lipid structure) could be slightly increased for better visibility in the final size. Perhaps the spectra could be a bit larger as well.
2) The list inside the brackets is a bit confusing: Berger is a lipid model whereas Amber-related lipid models discussed in the MS are called GAFFlipid and Lipid14. We could simply emphasise the completeness of the study by replacing this text by e.g. "MD simulations with 12 lipid models"

**Comment by ohsOllila** [comment]
I am happy with the latest figure by Marius, with or without the suggestions by Matti. It seems that this style of figure is getting a little bit more support than the other one, thus I will use this. I will either use the one already there, or the updated version if it will be done.

**Comment by ohsOllila** [comment]
I used the picture by Matti in the front page of the blog.

**Comment by mretegan** [comment]
The final figure including Matti's comments.

![toc](https://cloud.githubusercontent.com/assets/93124/9379078/ed2bceaa-4726-11e5-9f1e-d897bb7bd97d.png)

**Comment by ClaireLoison** [comment]
This final picture is very nice !

**Comment by patrickfuchs** [comment]
I think so too! One remark though, the theta angle should be between the C-H bond and the normal to the membrane (the magnetic field in the NMR experiments). The way it is drawn looks like it is the angle between C-H and O-P bonds.

**Comment by mretegan** [comment]
I realized that when I made the first figure, but I could not find a good way to place the arrows without making the whole thing look bad. Maybe labeling and slightly rotating the vertical arrow does the trick.
![toc](https://cloud.githubusercontent.com/assets/93124/9382791/0b2950ae-4744-11e5-9ac4-ea9ec83960fe.png)

**Comment by patrickfuchs** [comment]
Thanks, I think it's better like this. It is now clear it has nothing to do with the O-P bond, and the labeling makes it clear we're talking about the normal to the membrane.

**Comment by lucamonticelli** [comment]
I like the new figure (thanks Patrick for the precision), and I don't want to make a fuss about the lipid bilayer in vacuum, but let me answer more specifically to Marius' point:
"The only information that image has to provide is that MD simulations were performed on lipid bilayers, which it does". I think it does in a slightly misleading way. Having spoken to several experimentalists over the past 15 years, I know many of them get confused about what we simulate: the figure shows a lipid bilayer in vacuum, which is not what we simulate. No big deal for a specialist, but misleading for everybody else.

**Comment by ffavelar** [comment]
The improvements over the TOC1 are really great, and regarding the comments of Luca I think the bilayer it could look more like one the images mentioned by Marius of Slipids:
![screen shot 2015-08-20 at 8 17 17 pm](https://cloud.githubusercontent.com/assets/11906523/9400570/7456e2c8-4788-11e5-8e58-ba5f88459f71.png)
with the corresponding zoom-in lines.

**Comment by markussmiettinen** [comment]
Just a quick note. According to my count we have 13 force fields:
1. Berger
2. Högberg08
3. CHARMM36-UA
4. Tjörnhammar14
5. Poger
6. CHARMM36
7. Slipid
8. GAFFlipid
9. Chiu
10. Kukol
11. Ulmschneiders
12. Lipid14
13. MacRog

**Comment by mretegan** [comment]
Updated the number and the bilayer representation. I will make another pull request with the .svg file once the issue is closed.
![toc](https://cloud.githubusercontent.com/assets/93124/9404492/72569c9e-47f0-11e5-82e3-4dd3fbca3a9b.png)

**Comment by ohsOllila** [comment]
This version will be used. I am about to submit.
