### ISSUE TITLE
Around which values are the +-0.2 sweet spots in Fig. 2?

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/nmrlipids.blogspot.fi#66]
Is it around average of experimental values or something else? We need to know this for the second reply to the reviwers: https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/HGmodelMANUSCRIPT/REPLYtoREVIEWER2.txt

**Comment by markussmiettinen** [comment]
The reviewer is suggesting that the sweet spots would not be all of the same size, but that some would be broader and some narrower. This is not the the case, as is clear from the [plotting script](https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/DATAreportediINblog/plotDataSorted.gpl): All sweet spots are exactly 0.04 units. This width was chosen to roughly reflect the uncertainty of ±0.02.

As the reviewer is not asking around what value the sweet spots are centered, I would not bring this subject up in the answer. (Anyway, for those interested: The centers are at the average, rounded to 0.001, of the extremal experimental values.)

**Comment by markussmiettinen** [comment]
I updated the [reply](https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/HGmodelMANUSCRIPT/REPLYtoREVIEWER2.txt) based on my suggestion above.

**Comment by ohsOllila** [comment]
I did add the information about the center of the sweet spots into the text to be exact: https://github.com/NMRLipids/nmrlipids.blogspot.fi/commit/93323daa80942600868fec2526df61c2261d70ba

I think that this is settled now.
