### ISSUE TITLE
Updated order parameter numbers for Berger POPC in full hydration

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/nmrlipids.blogspot.fi#67]
When doing the figure for NMRLipids II project I noticed there had been a failure in running the script to calculate order parameters for Berger POPC in full hydration (probably due to exceeded disk quota). Rerunning did induce small changes to the numbers (less than 0.02). Unfortunately, this data is shown in almost all figures in the manuscript. 

I have now updated the data into the data folder: https://github.com/NMRLipids/nmrlipids.blogspot.fi/commit/2769adb462a41762fc71c82928fe2bcd17148361

However, due the gnuplot version issues I cannot redo the figures. 

Sorry about that.

**Comment by ohsOllila** [comment]
I was able to find the correct Gnuplot version and fixed this in https://github.com/NMRLipids/nmrlipids.blogspot.fi/commit/24765db27974a48f6cbde6f8207a91009b893ed3

If anyone interested, the correct version was Version 4.6 patchlevel 4

**Comment by markussmiettinen** [comment]
There were some problems with the previous update of the plot:

1) The larger POPC Berger g1 value was outside of the figure.

2) The simulation data points were not organized to increasing order.

I [fixed these issues](https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/9a7617c60287489405da4c6e653bc442e4b709c5/DATAreportediINblog/comparisonSorted.pdf) and created also a [Gnuplot 5.0 -version of the plotting script](https://github.com/NMRLipids/nmrlipids.blogspot.fi/commit/44e1d9fea897384d98cc8866c3f33a1328c9e5d3).
