### ISSUE TITLE
Figure 2 vs Table 1 (mismatch)

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/nmrlipids.blogspot.fi#7]
Table 1 and the caption of Figure 2 do not currently match. At least these mismatches should be sorted out (by tuning the fig caption and the table):

1) MacRog POPC. In Fig 2 three different full hydration simulations were used.

2) CHARMM36 DPPC. In Fig 2 also the data from the original CHARMM36 publication was used.

3) GAFFlipid DPPC. In Fig 2 also the data from the original GAFFlipid publication was used.

**Comment by ohsOllila** [comment]
There are also the recently added results from CHARMM36-UA model which should be added into this plot. The results are here:
https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/DATAreportediINblog/DPPC/CHARMM36UA-323K_blogged-25-3-15.dat

**Comment by markussmiettinen** [comment]
I have added the new CHARMM36-UA data (mentioned above by Samuli) in Fig 2 and Figure 4. They had already been added to Table 1.

I also listed all the three MacRog simulations (mentioned above by myself) in Table 1.

And, I put preliminary rows dealing with mismatches 2) and 3) (mentioned above by myself) in Table 1. These should still be tuned, then I will close this issue.
