### ISSUE TITLE
Simple request: MDP for slipids

### ISSUE THREAD

**Issue by jandom** [NMRLipids/nmrlipids.blogspot.fi#70]
Hi Samuli,

How is it going? I was just looking at this... I'm assuming you have the mdp for gromacs to be used with Slipids? People tell me it's constant surface area although I assumed it will be NPT. I can of course work back from the tpr you posted ;) 
- Jan

**Comment by ohsOllila** [comment]
There is mdp available for DPPC with slipids:
https://github.com/NMRLipids/nmrlipids.blogspot.fi/tree/master/MD_files/Slipids
http://dx.doi.org/10.5281/zenodo.13287.
For POPC simulation the mdp seems not to be available. Both should be in NPT. 

There is also recently reported data for NMRlipids II but the files are not yet shared for that:
https://github.com/NMRLipids/lipid_ionINTERACTION/pull/26

**Comment by jandom** [comment]
Ah, perfect - resolved it completely for me. Thank you!
