### ISSUE TITLE
Citation warnings with latex when compiling  HGmodel_ACStemplate.tex

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/nmrlipids.blogspot.fi#8]
When compiling this
https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/HGmodelMANUSCRIPT/HGmodel_ACStemplate.tex,
it gives warnings from some citations. These seems to be citations in the tables. I could not fix it with moderate effort so I have ignored this since the pdf looks reasonable. It migh not be necessary to solve this, but it would be nice.

**Comment by HubLot** [comment]
Could you provide the citations warning ? I would like to check if I have the same.

**Comment by ohsOllila** [comment]
I added log file from pdflatex:
https://github.com/NMRLipids/nmrlipids.blogspot.fi/blob/master/HGmodelMANUSCRIPT/HGmodel_ACStemplate.log

The affiliation errors begin from line 582 and citation warnings from line 896.

**Comment by HubLot** [comment]
Strange...
I do not have the affiliations errors and for the citations warnings:
- I don't have the ones between 896-1280.
- I do have the ones from 1280 to the end.

Do you use the classic workflow to compile: ?
- pdflatex HGmodel_ACStemplate.tex
- bibtex  HGmodel_ACStemplate
- pdflatex HGmodel_ACStemplate.tex
- pdflatex HGmodel_ACStemplate.tex

I'll look into it and I'll try to provide a valid Makefile to easily recompile the manuscript.

**Comment by HubLot** [comment]
In fact,  it's because we used references in the section _supplementary information_ (present after the `\bibliography{refs}`) and theses references never appeared before in the manuscript ([source](http://compgroups.net/comp.text.tex/can-citet-work-with-achemso-and-mciteplus/1953886)). But it's still working anyway.

Maybe it could be better to create a separate file (hence a separate bibliography) for the SI? Or make a second bibliography for the SI.

**Comment by ohsOllila** [comment]
I think that before submission we will create anyway separate file for supplementary information. I have kept those in the same file now since it is more convenient for people not need to download several separate files. We can move the bibliography after the supplementary for now, if it helps.

**Comment by HubLot** [comment]
Okay so for the moment we can leave it as is. The errors can be silent.
We can keep the issue open until we made separate files for the SI.

**Comment by ohsOllila** [comment]
I moved the bibliography after the supplementary information and there is no errors anymore. Before submission we will make a separate file for supplementary. I will close this.
