### ISSUE TITLE
Affiliation problem in HGmodel_ACStemplate.tex 

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/nmrlipids.blogspot.fi#9]
It seems to me that the ACS *tex template format (HGmodel_ACStemplate.tex) accepts only 10 different affiliations. When there is more it gives this kind of warning:

! Missing number, treated as zero.
<to be read again> 
                   $
l.149 \begin{document}

?  

This has to somehow solved before submission. This is the reason why affiliations are not up-to-date.

**Comment by HubLot** [comment]
I cannot reproduce this bug. 
I'm using the achemso package version 3.8e. From the log you provided, you're using the 3.7a version.
Try to upgrade to the latest version of achemso to see if the bug still occurs.

**Comment by ohsOllila** [comment]
I updated the version and there is no problem anymore. Thanks!
